Repository recurly/recurly-js, pull requests merged in 2019-09, with the labels that each got.

#525 Emit PayPal cancel event on frame close
  lib/recurly/frame.js
  lib/recurly/paypal/strategy/direct.js
  test/frame.test.js
  test/paypal/strategy/direct.test.js
Labels: changelog, enhancement

#544 Add eslint
  .editorconfig
  .eslintrc.js
  Makefile
  lib/recurly.js
  lib/recurly/adyen.js
  lib/recurly/apple-pay.js
  lib/recurly/bus.js
  lib/recurly/coupon.js
  lib/recurly/errors.js
  lib/recurly/frame.js
  lib/recurly/fraud.js
  lib/recurly/hosted-field.js
  lib/recurly/hosted-fields.js
  lib/recurly/message.js
  lib/recurly/paypal/index.js
  lib/recurly/paypal/strategy/braintree.js
  lib/recurly/paypal/strategy/direct.js
  lib/recurly/paypal/strategy/index.js
  lib/recurly/pricing/checkout/attachment.js
  lib/recurly/pricing/checkout/calculations.js
  lib/recurly/pricing/checkout/index.js
  lib/recurly/pricing/index.js
  lib/recurly/pricing/subscription/attachment.js
  lib/recurly/pricing/subscription/calculations.js
  lib/recurly/pricing/subscription/embedded.js
  lib/recurly/pricing/subscription/index.js
  lib/recurly/reporter.js
  lib/recurly/risk/risk-concern.js
  lib/recurly/risk/risk.js
  lib/recurly/risk/three-d-secure/strategy/adyen.js
  lib/recurly/risk/three-d-secure/strategy/braintree.js
  lib/recurly/risk/three-d-secure/strategy/strategy.js
  lib/recurly/risk/three-d-secure/strategy/stripe.js
  lib/recurly/risk/three-d-secure/strategy/test.js
  lib/recurly/risk/three-d-secure/strategy/wirecard.js
  lib/recurly/risk/three-d-secure/three-d-secure.js
  lib/recurly/tax.js
  lib/recurly/validate.js
  lib/recurly/worker.js
  lib/util/dom.js
  lib/util/normalize.js
  lib/util/parse-card.js
  lib/util/web-storage.js
  package-lock.json
  package.json
Labels: tests & build

#546 adds error emission instead of throwing in Fraud
  lib/recurly.js
  lib/recurly/fraud.js
Labels: bug, changelog

#543 implement CIT for sagepay
  lib/recurly/risk/three-d-secure/strategy/sage-pay.js
  lib/recurly/risk/three-d-secure/three-d-secure.js
  test/risk/three-d-secure/strategy/sage-pay.test.js
  test/server/fixtures/tokens/action-token-sage-pay.json
Labels: changelog, enhancement, in progress

#547 Adds 3D Secure support for Worldpay
  karma.conf.js
  lib/recurly/bus.js
  lib/recurly/errors.js
  lib/recurly/risk/risk.js
  lib/recurly/risk/three-d-secure/index.js
  lib/recurly/risk/three-d-secure/strategy/strategy.js
  lib/recurly/risk/three-d-secure/strategy/worldpay.js
  lib/recurly/risk/three-d-secure/three-d-secure.js
  lib/recurly/token.js
  test/risk.test.js
  test/risk/three-d-secure.test.js
  test/risk/three-d-secure/strategy/worldpay.test.js
  test/server/fixtures/risk/preflights.js
  test/server/fixtures/tokens/action-token-worldpay.json
  test/server/fixtures/tokens/index.js
  test/server/index.js
  test/util/group-by.test.js
Labels: enhancement

#549 Fixes loading Braintree libraries
  lib/recurly/risk/three-d-secure/strategy/braintree.js
Labels: bug, changelog

#548 Updates eslint config to avoid escaping quotes in strings
  .eslintrc.js
  Makefile
  lib/recurly/errors.js
  lib/recurly/frame.js
  lib/recurly/paypal/strategy/direct.js
  lib/recurly/paypal/strategy/index.js
  lib/recurly/validate.js
Labels: tests & build

#556 Fixes Braintree authentication amount display
  lib/recurly/risk/three-d-secure/strategy/braintree.js
  test/risk/three-d-secure/strategy/braintree.test.js
  test/server/fixtures/tokens/action-token-adyen-3ds1.json
  test/server/fixtures/tokens/action-token-adyen-fingerprint.json
  test/server/fixtures/tokens/action-token-adyen.json
  test/server/fixtures/tokens/action-token-braintree.json
  test/server/fixtures/tokens/action-token-sage-pay.json
  test/server/fixtures/tokens/action-token-stripe.json
  test/server/fixtures/tokens/action-token-test.json
  test/server/fixtures/tokens/action-token-wirecard.json
  test/server/fixtures/tokens/action-token-worldpay.json
Labels: bug

#555 Renders Wirecard 3DS challenge as an iframe instead of new window
  lib/recurly/risk/three-d-secure/strategy/wirecard.js
  test/risk/three-d-secure/strategy/wirecard.test.js
Labels: enhancement

#558 Browserstack
  .travis-pre.sh
  .travis.yml
  Makefile
  README.md
  karma.ci.conf.js
  karma.conf.js
  lib/recurly/request.js
  package-lock.json
  package.json
  test/configure.test.js
  test/coupon.test.js
  test/frame.test.js
  test/paypal/paypal.test.js
  test/paypal/strategy/braintree.test.js
  test/paypal/strategy/direct.test.js
  test/paypal/strategy/strategy.test.js
  test/risk/three-d-secure.test.js
  test/risk/three-d-secure/strategy.test.js
  test/server/index.js
  test/support/helpers.js
  test/worker.test.js
Labels: tests & build
