Repository recurly/recurly-js, pull requests merged in 2020-05, with the labels that each got.

#602 Moves koa-better-http-proxy dependency
  package-lock.json
  package.json
Labels: dependency

#603 Throws missing plan code error if plan is an empty string
  lib/recurly/plan.js
Labels: enhancement

#601 Adds DefinitelyTyped github action
  .github/workflows/dt.yaml
  types/lib/3d-secure.d.ts
  types/lib/address.d.ts
  types/lib/adyen.d.ts
  types/lib/apple-pay.d.ts
  types/lib/bank-account.d.ts
  types/lib/configure.d.ts
  types/lib/elements.d.ts
  types/lib/emitter.d.ts
  types/lib/error.d.ts
  types/lib/gift-card.d.ts
  types/lib/paypal.d.ts
  types/lib/pricing/checkout.d.ts
  types/lib/pricing/index.d.ts
  types/lib/pricing/promise.d.ts
  types/lib/pricing/subscription.d.ts
  types/lib/recurly.d.ts
  types/lib/token.d.ts
  types/lib/validate.d.ts
Labels: tests & build

#607 Adds CORP header to dev server
  webpack.config.js
Labels: tests & build
