Repository recurly/recurly-js, pull requests merged in 2020-07, with the labels that each got.

#623 Adds open source attribution comment
  index.js
  webpack.config.js
Labels: tests & build

#614 Adds Becs support
  lib/recurly/bank-account.js
  lib/recurly/validate.js
  test/e2e/recurly.test.js
  test/e2e/support/helpers.js
  test/server/fixtures/tokens/index.js
  test/server/views/e2e/bank-account-becs.html.ejs
  test/types/bank-account.ts
  test/unit/bank-account.test.js
  types/lib/bank-account.d.ts
Labels: new feature

#618 Fixes previous tabbing for Elements on non-mobile browsers
  .travis.yml
  Makefile
  karma.ci.conf.js
  karma.conf.js
  lib/recurly/element/element.js
  package-lock.json
  package.json
  test/conf/browserstack.js
  test/e2e/behavior.tabbing.test.js
  test/e2e/recurly.test.js
  test/e2e/support/helpers.js
  test/server/views/e2e/_foot.html.ejs
  test/server/views/e2e/_head.html.ejs
  test/unit/element.test.js
  test/unit/support/fixtures.js
  wdio.ci.conf.js
  wdio.conf.js
Labels: bug

#628 Adds e2e test for cvv requirement
  package-lock.json
  test/e2e/recurly.test.js
Labels: tests & build

#629 Adds support to tokenize tax_identifier
  lib/recurly/token.js
  lib/recurly/validate.js
  test/server/fixtures/token/index.js
  test/server/index.js
  test/unit/support/fixtures.js
  test/unit/token.test.js
  test/unit/validate.test.js
Labels: new feature
