Repository recurly/recurly-js, pull requests merged in 2020-04, with the labels that each got.

#584 Adds support for typescript declaration generation and testing
  .travis.yml
  Makefile
  package-lock.json
  package.json
  test/types/3d-secure.ts
  test/types/adyen.ts
  test/types/apple-pay.ts
  test/types/bank-account.ts
  test/types/configure.ts
  test/types/elements.ts
  test/types/gift-card.ts
  test/types/index.d.ts
  test/types/paypal.ts
  test/types/pricing/checkout.ts
  test/types/pricing/subscription.ts
  test/types/token/elements.ts
  test/types/token/hosted-field.ts
  test/types/tsconfig.json
  test/types/tslint.json
  test/types/validate.ts
  types/3d-secure.ts
  types/address.ts
  types/adyen.ts
  types/apple-pay.ts
  types/bank-account.ts
  types/configure.ts
  types/create-types.js
  types/dt-header
  types/elements.ts
  types/emitter.ts
  types/error.ts
  types/gift-card.ts
  types/paypal.ts
  types/pricing/checkout.ts
  types/pricing/index.ts
  types/pricing/promise.ts
  types/pricing/subscription.ts
  types/recurly.ts
  types/token.ts
  types/tsconfig.json
  types/validate.ts
Labels: new feature, tests & build

#594 Increases the report collation period to 30 seconds
  lib/recurly/worker.js
  test/unit/worker.test.js
Labels: enhancement

#596 Restores iOS 13 CI tests
  .travis.yml
Labels: tests & build

#598 Updates dependencies
  .travis.yml
  package-lock.json
  package.json
  test/types/recurly-error.ts
  test/types/tsconfig.json
  wdio.ci.conf.js
Labels: dependency, tests & build

#599 Caches plan requests
  lib/recurly/plan.js
Labels: enhancement

#600 Sends requested currency in `GET /apple_pay/info` requests
  lib/recurly/apple-pay.js
Labels: enhancement
