Repository recurly/recurly-js, pull requests merged in 2020-03, with the labels that each got.

#586 Adds ability to set Recurly.js URL in e2e tests
  .jshintrc
  test/server/index.js
Labels: enhancement, tests & build

#587 Specifies local and debug options for unit tests run in Browserstack
  karma.ci.conf.js
Labels: tests & build

#589 Forces Browserstack local connection and identifier in Karma CI test runs
  karma.ci.conf.js
Labels: tests & build

#590 Adds union pay
  lib/recurly/validate.js
  lib/util/deep-assign.js
  test/unit/validate.test.js
Labels: enhancement
